name: simulationODEexamples-environment
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pytest
  - six
  - numpy
  - sympy
  - scipy
  - matplotlib>=2.0
  - pandas
  - seaborn
  - jupyterlab_widgets
  - ipywidgets
  - pip
  - nodejs
  - pip:
      - stimator